version: '3.8'

services:
  portfolio-tracker:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PUBLIC_API_KEY=${PUBLIC_API_KEY}
      - PORT=3001
      - DATABASE_URL=postgresql://portfolio_user:${DB_PASSWORD}@postgres:5432/portfolio_tracker
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: portfolio_tracker
      POSTGRES_USER: portfolio_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U portfolio_user -d portfolio_tracker"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
